# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HistoryWindow(object):
    def setupUi(self, HistoryWindow):
        HistoryWindow.setObjectName("HistoryWindow")
        HistoryWindow.resize(740, 600)
        self.centralwidget_history = QtWidgets.QWidget(HistoryWindow)
        self.centralwidget_history.setObjectName("centralwidget_history")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget_history)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 8)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout.addWidget(self.pushButton_back)
        self.label_page = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_page.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.label_page.setFont(font)
        self.label_page.setScaledContents(True)
        self.label_page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page.setIndent(0)
        self.label_page.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout.addWidget(self.label_page)
        self.pushButton_next = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.spinBox_page = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.spinBox_page.setFont(font)
        self.spinBox_page.setProperty("value", 1)
        self.spinBox_page.setObjectName("spinBox_page")
        self.horizontalLayout.addWidget(self.spinBox_page)
        self.pushButton_go = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_go.setFont(font)
        self.pushButton_go.setObjectName("pushButton_go")
        self.horizontalLayout.addWidget(self.pushButton_go)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget_history)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 791, 531))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.conLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.conLayout.setContentsMargins(0, 5, 0, 0)
        self.conLayout.setSpacing(1)
        self.conLayout.setObjectName("conLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.conLayout.addWidget(self.tableWidget)
        self.imglabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.imglabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.imglabel.setText("")
        self.imglabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imglabel.setObjectName("imglabel")
        self.conLayout.addWidget(self.imglabel)
        HistoryWindow.setCentralWidget(self.centralwidget_history)
        self.menubar = QtWidgets.QMenuBar(HistoryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 18))
        self.menubar.setObjectName("menubar")
        HistoryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HistoryWindow)
        self.statusbar.setObjectName("statusbar")
        HistoryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HistoryWindow)
        QtCore.QMetaObject.connectSlotsByName(HistoryWindow)

    def retranslateUi(self, HistoryWindow):
        _translate = QtCore.QCoreApplication.translate
        HistoryWindow.setWindowTitle(_translate("HistoryWindow", "MainWindow"))
        self.pushButton_back.setText(_translate("HistoryWindow", "前一頁"))
        self.label_page.setText(_translate("HistoryWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">1/100</span></p></body></html>"))
        self.pushButton_next.setText(_translate("HistoryWindow", "後一頁"))
        self.pushButton_go.setText(_translate("HistoryWindow", "頁面跳轉"))

